bind_address: '127.0.0.1'
bind_port: 4433
remote_address: '127.0.0.1'
remote_port: 8000
sni: 'neo-term-repo.proce.top'
cert: '/Users/dmls/Desktop/trojan-server/testdata/neo-term-repo.proce.top.crt'
pk: '/Users/dmls/Desktop/trojan-server/testdata/neo-term-repo.proce.top.key'

